#!/bin/bash
# shellcheck disable=SC2312

# Plugin Name: check_swap
# Description: Check system swap
# Date: 02/10/2025

# Flags
ALLOW_ZERO_INPUT=true
PREFIX="SWAP"

# Global Variables
WARNING_LEVEL=50
CRITICAL_LEVEL=70

# Main
function main()
{
    local swap_total swap_free swap_used
    local swap_used_pct swap_warn_pct swap_crit_pct
    local f_swap_total f_swap_free f_swap_used
    local message data

    # Error if can't read swap info
    if ! grep -q "SwapTotal" /proc/meminfo; then
        handle_unknown "Unable to read /proc/meminfo"
    fi

    # Get swap values from /proc/meminfo
    swap_total=$(awk '/SwapTotal/ {print $2}' /proc/meminfo)
    swap_free=$(awk '/SwapFree/ {print $2}' /proc/meminfo)
    swap_used=$((swap_total - swap_free))

    # Error if no swap
    if (( swap_total == 0 )); then
        handle_critical "No swap configured"
    fi

    # Calculate swap free percentage
    swap_used_pct=$(awk -v used="$swap_used" -v total="$swap_total" 'BEGIN { printf "%.1f\n", 100 * used / total }')
    swap_warn_pct=$(awk "BEGIN {print int(($WARNING_LEVEL / 100) * $swap_total )}")
    swap_crit_pct=$(awk "BEGIN {print int(($CRITICAL_LEVEL / 100) * $swap_total )}")

    # Generate output
    f_swap_total=$(format_bits "$swap_total")
    f_swap_free=$(format_bits "$swap_free")
    f_swap_used=$(format_bits "$swap_used")
    message="${swap_used_pct}% swap used (${f_swap_used} used of ${f_swap_total}, ${f_swap_free} free)"
    data="swap_total=${swap_total}kib;;;; swap_used=${swap_used}kib;${swap_warn_pct};${swap_crit_pct};; swap_free=${swap_free}kib;;;;"

    # Compare to threshold values
    if (( $(echo "${swap_used_pct} >= ${CRITICAL_LEVEL}" | bc -l) )); then
        handle_critical "${message}" "${data}"
    elif (( $(echo "${swap_used_pct} >= ${WARNING_LEVEL}" | bc -l) )); then
        handle_warning "${message}" "${data}"
    elif (( $(echo "${swap_used_pct} >= 0" | bc -l) )); then
        handle_ok "${message}" "${data}"
    else
        handle_unknown "Invalid swap value ${data}"
    fi

}

# Format byte values base on magnitude
function format_bits() {
    local kb="$1"
    local unit="KiB"
    local value="$kb"

    if (( kb >= 1024 * 1024 * 1024 )); then
        value=$(awk "BEGIN {printf \"%.2f\", $kb/1073741824}")
        unit="TiB"
    elif (( kb >= 1024 * 1024 )); then
        value=$(awk "BEGIN {printf \"%.2f\", $kb/1048576}")
        unit="GiB"
    elif (( kb >= 1024 )); then
        value=$(awk "BEGIN {printf \"%.2f\", $kb/1024}")
        unit="MiB"
    fi

    echo "${value}${unit}"
}

# Usage (-h parameter)
function usage()
{
cat <<EOF
  Usage: $0 [ -h ] [ -c value ] [ -w value ]
    -h, --help      : Print this screen
    -c, --critical  : Critical percentage of swap used [Default: ${CRITICAL_LEVEL}%]
    -w, --warning   : Warning percentage of swap used [Default: ${WARNING_LEVEL}%]
EOF
    exit 0
}

# Process Arguments
function process_arguments()
{
    # Check if no arguments is allowed
    if [[ "${ALLOW_ZERO_INPUT}" = false ]] && [[ $# -eq 0 ]]; then
        handle_unknown "No parameters given"
    fi

    # Define short and long options
    SHORTOPTS=h,c:,w:
    LONGOPTS=help,critical:,warning:

    # Parse options using getopt
    OPTIONS=$(getopt --options=$SHORTOPTS --longoptions=$LONGOPTS --name "$0" -- "$@")
    if [[ $? -ne 0 ]]; then
        handle_unknown "Failed to parse arguments"
    fi

    # Reorder positional parameters
    eval set -- "${OPTIONS}"

    while true; do
        case "$1" in
            -h|--help)
                usage
                ;;
            -c|--critical)
                CRITICAL_LEVEL="$2"
                shift 2
                ;;
            -w|--warning)
                WARNING_LEVEL="$2"
                shift 2
                ;;
            --)
                shift
                break
                ;;
            *)
                handle_unknown "Unknown option: $1"
                ;;
        esac
    done

    # Validate warning and critical values
    if (( $(echo "${WARNING_LEVEL} >= ${CRITICAL_LEVEL}" | bc -l) )); then
        handle_unknown "Warning thresholds must be lower than critical thresholds"
    fi
    main
}

# Handle OK / Warning / Critical / Unknown
function handle_ok() {
    local message="${1:-}"
    local perfdata="${2:-}"
    echo "${PREFIX:+${PREFIX} }OK - ${message}${perfdata:+ | ${perfdata}}"
    exit 0
}

function handle_warning() {
    local message="${1:-}"
    local perfdata="${2:-}"
    echo "${PREFIX:+${PREFIX} }WARNING - ${message}${perfdata:+ | ${perfdata}}"
    exit 1
}

function handle_critical() {
    local message="${1:-}"
    local perfdata="${2:-}"
    echo "${PREFIX:+${PREFIX} }CRITICAL - ${message}${perfdata:+ | ${perfdata}}"
    exit 2
}

function handle_unknown() {
    local message="${1:-}"
    local perfdata="${2:-}"
    echo "${PREFIX:+${PREFIX} }UNKNOWN - ${message}${perfdata:+ | ${perfdata}}"
    exit 3
}

# Core
process_arguments "${@}"