# Zips all custom check-plugins as file for install 

name: Zip check plugins

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}

        
      - name: Zip release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: check-plugins.zip
          exclusions: '/.git* /*notifications/* /*templates/* /*archive/* README.md'
        
      - name: Upload release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "check-plugins.zip"
          token: ${{ secrets.GH_TOKEN }}
