# Zips all custom check-plugins as file for install 

name: Zip check plugins

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Zip release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: check-plugins.zip
          exclusions: '/.git* /notifications README.md'
      
      - name: Upload release
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: "check-plugins.zip"
          token: ${{ secrets.GITHUB_TOKEN }}